version: '2'
networks:
  app-network:
services:
  app:
    build: .
    #image:  prisys/apphotel:latest
    command: bash ./app.sh
    environment:
      - WORKERS=5
      - N_ITERATIONS=10e4
      - TIMEOUT=0
    ports:
      - '27017:27017'
    networks:
      - app-network