version: '2'
networks:
  app-network:
services:
  app:
    image:  prisys/apphotel:latest
    command: bash ./app.sh
    environment:
      - WORKERS=5
    ports:
      - '27017:27017'
    networks:
      - app-network